// filepath: k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: security-dashboard
  template:
    metadata:
      labels:
        app: security-dashboard
    spec:
      containers:
      - name: dashboard
        image: yourdockerhubusername/security-dashboard:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: security-dashboard-service
spec:
  selector:
    app: security-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer